# Generated by Django 4.2.2 on 2023-07-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
